### PR TITLE
update dependencies, and replace gama11/highlighter with docpad highlightjs

### PR DESCRIPTION
**Pull request by ninjamuffin99**
simply updates some of the docpad dependencies to their latest "stable" versions

did remove one that went unused (docpad-plugin-gist and graceful-fs)
i believe all of these might still be outdated, since docpad changed their plugin system, and I think the thumbnails plugin was still giving me grief, so these are the latest versions of the OLD plugin v1 format

``` bash
> npm outdated

Package                   Current  Wanted  Latest  Location                               Depended by
docpad                     6.79.4  6.79.4  6.83.2  node_modules/docpad                    haxeflixel.com
docpad-plugin-cleanurls    2.11.0  2.11.0  2.12.1  node_modules/docpad-plugin-cleanurls   haxeflixel.com
docpad-plugin-eco           2.1.0   2.1.0   2.8.0  node_modules/docpad-plugin-eco         haxeflixel.com
docpad-plugin-less          2.5.1   2.5.1  2.10.0  node_modules/docpad-plugin-less        haxeflixel.com
docpad-plugin-livereload    2.9.0   2.9.0  2.11.0  node_modules/docpad-plugin-livereload  haxeflixel.com
docpad-plugin-marked        2.4.0   2.4.0  2.10.0  node_modules/docpad-plugin-marked      haxeflixel.com
docpad-plugin-partials     2.12.0  2.12.0  2.14.0  node_modules/docpad-plugin-partials    haxeflixel.com
docpad-plugin-repocloner    2.3.1   2.3.1   2.8.0  node_modules/docpad-plugin-repocloner  haxeflixel.com
docpad-plugin-services      2.7.0   2.7.0  2.12.0  node_modules/docpad-plugin-services    haxeflixel.com
```

### EDIT: PT 2: SYNTAX HIGHLIGHTING
Added highlightjs plugin for docpad, thus removing the need for gama11/highlight step in the github actions. this also enables syntax highlighting when building locally

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
if nothing looks out of the ordinary, I'll toss this a merge @Geokureli

**Comment by Geokureli** [comment]
I'm down with this change, in theory, but CI is failing with some crazy errors

**Comment by ninjamuffin99** [comment]
yeah I think the last piece to get it fixed is to fix the syntax highlighting ! which ive been poking at just now

**Review by Geokureli — APPROVED** [review]
this stuff is over my head, i trust you

**Pull request merged**
