### PR TITLE
Flixel community blog post

### PR DESCRIPTION
**Pull request by MSGhero**
Rough draft. I'll add the links and pictures, so I'm mainly looking for feedback on its content.

### CODE REVIEW

**Comment by Gama11** [comment]
Github -> GitHub. Looks great apart from that! :)

**Comment by starry-abyss** [comment]
Also Flixel -> HaxeFlixel ? :-P

**Comment by MSGhero** [comment]
I think if someone gets to the HF website, it's clear what Flixel is referring to. I also clarified it in the previous post.

I assume I should include something about Patreon at the end, not sure if that's really a community I can include in the body.

**Comment by Gama11** [comment]
Wasn't the last post already about Patreon? Doesn't seem necessary to mention it again.

**Comment by MSGhero** [comment]
Updated.

**Comment by Gama11** [comment]
Perfect!

**Pull request merged**
