### PR TITLE
Port Documentation pages, and REMOVE DOCPAD

### PR DESCRIPTION
**Pull request by ninjamuffin99**
I will let @Geokureli do the honors of merging this.

- Does a buncho configs for prettier, standardjs, and liquid for basic tests / linting / formatting
- Ports the /documentation pages to 11ty
- Removes most of the docpad related code. Site is fully built with 11ty for it's static site generation
- Likely more stuff but i forget!

There's still some things needed to be done before a new site publish, but this is one of the last BIG pieces!

Stuff left on the todo: #223

### CODE REVIEW

**Comment by Geokureli** [comment]
Mfkr it's Friday, i ain't merging shit

**Comment by ninjamuffin99** [comment]
omfg im so sad i might just close this pr...

**Comment by Geokureli** [comment]
do i preview these changes via dev.haxeflixel or on that ninjamuffin.github link?

**Comment by ninjamuffin99** [comment]
lemme get changes hosted via my own github actions!

**Comment by ninjamuffin99** [comment]
> do i preview these changes via dev.haxeflixel or on that ninjamuffin.github link?

you can preview the site at https://ninjamuffin99.github.io/haxeflixel.com !

this is now also setup where forks can easily build to their own github.io page, without having effect on the dev/master stuff here :)

**Comment by Geokureli** [comment]
I notice the tutorial code shows up in an less pleasant way:
Screenshot 2024-03-04 at 2 53 17 PM

compared to [the current version](https://haxeflixel.com/documentation/groundwork/):
Screenshot 2024-03-04 at 2 55 50 PM

**Comment by ninjamuffin99** [comment]
yeah right now thats still on the todo! this PR is just for the documentation pages in general being ported, getting the highlighting looking nice again is one of the last things on the current todo!
#245

**Comment by Geokureli** [comment]
what is the timeline, here? we wanna merge this and then finish the other tasks before publishing the new version? I wonder if it makes more sense to continue using a branch for these changes until they are ready to be published, that way we can add all those new blog posts that I'm too lazy to get around to. jk but, realistically, how long between this merge and when we can publish the new version?

**Comment by ninjamuffin99** [comment]
Likely this week! It would take maybe a "session" or two of me working on it to hopefully get it READY for final site publish and update. I think pushing things into dev branch would also be good and nice for testing around to people, making sure that everything works on site itself and no snafus occur. 
In any case, I do think this one is definitely *merge ready*, and then within the next few days I'll be able to finish up the remaining tasks to have the site in near perfect parity from the old site

**Comment by Geokureli** [comment]
okay, just wanted to make sure it wasn't gonna be a month more

**Comment by Geokureli** [comment]
yolo

**Pull request merged**
