### PR TITLE
Renaming Files for Blasting Agent Showcase

### PR DESCRIPTION
**Pull request by SeiferTim**
So... this was a ridiculous nightmare of trying to rename files to have the `꞉` character in the filename... but it should work, now.

### CODE REVIEW

**Comment by Gama11** [comment]
Lol, looks like you didn't bother deleting the old files :P:

**Comment by Gama11** [comment]
Damnit, now the layout is broken because the title it too long... -.-

**Comment by Gama11** [comment]
Feel free to fix that one yourself, I've had enough of CSS for today...

**Comment by SeiferTim** [comment]
Sorry! I'll see what I can do...

**Pull request merged**
