### PR TITLE
Odd verdure showcase

### PR DESCRIPTION
**Pull request by MondayHopscotch**
Add Odd Verdure to showcase page

### CODE REVIEW

**Review by ninjamuffin99 — APPROVED** [review]

**Comment by ninjamuffin99** [comment]
seems like very awesome game! I will play it ! thanks for PR !

**Comment by MondayHopscotch** [comment]
Looks like prettier failed because there wasn't a newline at the end of my .md file. It's quite minor (obviously), but if you would like the fix, it's sitting in this branch: https://github.com/MondayHopscotch/haxeflixel.com/tree/odd-verdure-prettier

**Comment by ninjamuffin99** [comment]
sure, thanks

**Comment by MondayHopscotch** [comment]
What is the release cadence for the website releasing? I was trying to show my buddy that I built this game with that it's in the showcase... but it doesn't look like it's been pushed up yet XD

**Comment by Geokureli** [comment]
It's up, now. Sorry about that, I forgot there's a master branch, some of the other repos only need a commit to dev to be released

**Pull request merged**
