### PR TITLE
New FlxLightPuzzle demo blog

### PR DESCRIPTION
**Pull request by MSGhero**
Looking for feedback.

### CODE REVIEW

**Comment by Gama11** [comment]
Looks good to me, but it seems strange to link to an external site for playing the demo. Perhaps we should put it up on https://haxeflixel.com/demos/ first (as well as make a new flixel-demos release)?

**Comment by MSGhero** [comment]
That’s true, yeah. I’ll have to PR that then.

**Comment by Gama11** [comment]
I've made a flixel-demos release and added the demo to the site, but I couldn't find a way to also add a HTML5 version of it (I think we'll need help from @impaler for that).. so whatever, let's just link to Newgrounds for now.

Feel free to add a description to the demo on the site if you want.

**Comment by Gama11** [comment]
Hm.. Somehow the blog post isn't showing up on the site, but it works fine when I build the site locally. Not sure what's going on, something wrong with deployment maybe..

**Comment by Gama11** [comment]
I restarted the Travis build, and this time it seems to have worked. \o/

Definitely something strange going on with deployment though:

```
Deploying to haxeflixel.com from branch master
Warning: Permanently added '[[secure]]:[secure]' (ECDSA) to the list of known hosts.
rsync: recv_generator: mkdir "/home/[secure]/www/haxeflixel.com/master/out" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
error with the rsync command
{ [Error: Command failed: rsync -e "ssh -oStrictHostKeyChecking=no -i /home/travis/build/HaxeFlixel/haxeflixel.com/scripts/deploy -p [secure]" --delete -avr /home/travis/build/HaxeFlixel/haxeflixel.com/out [secure]@[secure]:master
Warning: Permanently added '[[secure]]:[secure]' (ECDSA) to the list of known hosts.
rsync: recv_generator: mkdir "/home/[secure]/www/haxeflixel.com/master/out" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
```

**Pull request merged**
